---
collections:
  - name: redhat_cop.tower_configuration
    #version: 1.4.1
    version: devel
    #source: https://galaxy.ansible.com

  - name: awx.awx
    version: 19.1.0

  - name: ansible.tower
    version: 3.8.3
    #source: https://cloud.redhat.com/api/automation-hub/