---
collections:
  - name: redhat_cop.controller_configuration
    version: 2.1.5
    #source: https://galaxy.ansible.com

# # Need Ansible 2.10 for this to work
#   - name: https://github.com/redhat-cop/tower_configuration.git
#     type: git
#     version: devel

  # - name: awx.awx
  #   version: 19.1.0

  - name: ansible.controller
    version: 4.1.2
    source: https://console.redhat.com/api/automation-hub/
