 - name: Playbook to create the 'Workflow Example Project'
   hosts: localhost
   vars:
     - tower_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
   # - tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
   # - tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
     - tower_oauthtoken: "{{ lookup('env', 'TOWER_OAUTHTOKEN') }}"
   collections:
     - ansible.tower
     #- awx.awx
     - redhat_cop.tower_configuration

   pre_tasks:
     - name: Include vars from vars directory
       include_vars:
         dir: ./vars
         extensions: ["yml"]
       tags:
         - always

   roles:
       - {role: projects, when: tower_projects is defined, tags: projects}
       - {role: job_templates, when: tower_templates is defined, tags: job_templates}
       - {role: workflow_job_templates, when: tower_workflows is defined, tags: workflow_job_templates}