 - name: Playbook to create the 'Workflow Example Project'
  hosts: localhost
  connection: local
  vars:
    - org: "Default"
    - tower_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    # - tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    # - tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    - tower_oauthtoken: "{{ lookup('env', 'TOWER_OAUTHTOKEN') }}"
  collections:
    - ansible.tower

  pre_tasks:
    - name: Include vars from vars directory
      include_vars:
        dir: ./vars
        extensions: ["yml"]
      tags:
        - always

  roles:
    - {role: redhat_cop.tower_configuration.projects, when: tower_projects is defined, tags: projects}