# Needs
# Either: tower_hostname, tower_username, tower_password
# Or: tower_hostname, tower_oauthtoken 
- name: Playbook to create the Workflow Example Project
  hosts: localhost
  connection: local

  tasks:
    - name: Create project  
      tower_projects:
        - name: Workflow Example Project
          scm_type: git
          scm_url: https://github.com/nleiva/ansible-workshop.git
          scm_branch: main
          scm_clean: true
          description: Project created from code
          organization: "{{ org }}"
          wait: true
          update: true
          vars:
            - org: "Default"