- name: Workflow Unit work
  hosts: localhost
  #connection: local
  gather_facts: "{{ my_facts | default('no', true) }}"
  vars:
    - to_fail: false
    - tower_base_url: "https://{{ tower_hostname }}/api/v2/"

  tasks:
    - name: Print Job data
      debug:
        msg: |
          Username: {{ tower_user_name }}
          Job ID: {{ tower_job_id }}
          How the Job was started: {{ tower_job_launch_type }}
          Workflow Job Name that launched it: {{ tower_workflow_job_name | default('N/A', true) }}
          Workflow Job ID that launched it: {{ tower_workflow_job_id | default('N/A', true) }}

    - name: Get Workflow Node ID for this Job
      set_fact:
        tower_settings: "{{ lookup('ansible.tower.tower_api', endpoint) }}"
      register: result
      vars:
        endpoint: "workflow_job_nodes/?job_id={{ tower_job_id }}"

    # - name: DEBUG workflow
    #   debug:
    #     # msg: "{{ result | to_nice_json }}"
    #     msg: "{{ result.ansible_facts.tower_settings }}"

    - name: Get parent Workflow nodes for this Workflow Node
      set_fact:
        tower_settings: "{{ lookup('ansible.tower.tower_api', endpoint) }}"
      register: parents
      vars:
        endpoint: "workflow_job_nodes/?success_nodes={{ result.ansible_facts.tower_settings.id }}"

    # - name: DEBUG parents LENGTH
    #   debug:
    #     msg: "{{ parents.ansible_facts.tower_settings | length }}"

    # - name: DEBUG parents TYPE
    #   debug:
    #     msg: "{{ parents.ansible_facts.tower_settings | type_debug }}"

    # Exclusive OR (XOR) bol(a) != bol(b)
    - name: Check XOR
      include_tasks: xor_check.yml
      when: ( data | length == 2 ) and ( data | type_debug == "list" )
      vars:
          data: "{{ parents.ansible_facts.tower_settings }}"

    - name: Example using fail and when together
      fail:
        msg: This task has been marked to fail
      when: to_fail