- name: Workflow Unit work
  hosts: localhost
  #connection: local
  gather_facts: "{{ my_facts | default('no', true) }}"
  vars:
    - to_fail: false

  tasks:
    - name: Print Job data
      debug:
        msg: |
          Username: {{ tower_user_name }}
          Job ID: {{ tower_job_id }}
          How the Job was started: {{ tower_job_launch_type }}
          Workflow Job Name that launched it: {{ tower_workflow_job_name | default('N/A', true) }}
          Workflow Job ID that launched it: {{ tower_workflow_job_id | default('N/A', true) }}

    - name: Example using fail and when together
      fail:
        msg: This task has been marked to fail
      when: to_fail